"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var str1 = "sahil";
var str2 = "sahil";
var str3 = `Sahil`;
var age = 30;
var userName = "Sahil";
var info = `My name is ${userName} and age is ${age}`;
console.log(info);
var num = 100;
var data = num.toString();
var data = "" + num;
var boolData = true;
var data = boolData.toString();
var item = true;
var other;
other = item;
console.log(other);
var info1 = "Abu Jubair";
var str19 = "Hey I am Sahil";
