"use strict";
// var age: number;
// age = 25;
// console.log(`User age is ${age}`);
Object.defineProperty(exports, "__esModule", { value: true });
// var userName: string = "John Doe";
// console.log(`User name is ${userName}`);
// var college: string;
// college = "ABC University";
// console.log(`User college is ${college}`);
var a = undefined;
let numbers = [1, 2, 3];
